export const sample_foods: any[] = [
    {
      name: 'Coffee',
      price: 120.0,
      imageUrl: 'coffee1.gif',
      tags: ['Coffee'],
      favorite: false,
      createdAt: '2024-08-01T10:00:00Z',
    },
    {
      name: 'Mocktail',
      price: 120.0,
      imageUrl: 'juice1.gif',
      tags: ['Mocktail'],
      favorite: false,
      createdAt: '2024-06-01T10:00:00Z',
    },
    {
      name: 'Puff',
      price: 120.0,
      imageUrl: 'puff1.gif',
      tags: ['Puff'],
      favorite: false,
      createdAt: '2024-06-07T10:00:00Z',
    },
    {
      name: 'Croisaant',
      price: 120.0,
      imageUrl: 'croisaant1.gif',
      tags: ['Croisaant'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Coffee',
      price: 120.0,
      imageUrl: 'coffee2.gif',
      tags: ['Coffee'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Burger',
      price: 120.0,
      imageUrl: 'burger1.gif',
      tags: ['Burger'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Mocktail',
      price: 120.0,
      imageUrl: 'juice2.gif',
      tags: ['Mocktail'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Coffee',
      price: 120.0,
      imageUrl: 'coffee3.gif',
      tags: ['Coffee'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Croisaant',
      price: 120.0,
      imageUrl: 'croisaant2.gif',
      tags: ['Croisaant'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Puff',
      price: 120.0,
      imageUrl: 'puff2.gif',
      tags: ['Puff'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Croisaant',
      price: 120.0,
      imageUrl: 'croisaant3.gif',
      tags: ['Croisaant'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Coffee',
      price: 120.0,
      imageUrl: 'coffee4.gif',
      tags: ['Coffee'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Croisaant',
      price: 120.0,
      imageUrl: 'croisaant4.gif',
      tags: ['Croisaant'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
    {
      name: 'Croisaant',
      price: 120.0,
      imageUrl: 'croisaant5.gif',
      tags: ['Croisaant'],
      favorite: true,
      createdAt: '2024-05-01T10:00:00Z',
    },
  ];
  
  export const sample_tags: any[] = [
    { name: 'All', count: 14 },
    { name: 'Coffee', count: 4 },
    { name: 'Mocktail', count: 2 },
    { name: 'Puff', count: 2 },
    { name: 'Burger', count: 1 },
    { name: 'Croisaant', count: 5 },
  ];
  
  export const sample_users: any[] = [
    {
      name: 'John Doe',
      email: 'jhon@gmail.com',
      password: '1234',
      address: 'Toronto',
      isAdmin: true,
    },
    {
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '1234',
      address: 'Sudbury',
      isAdmin: false,
    },
    {
      name: 'Srushti Patel',
      email: 'shrupatel07@gmail.com',
      password: '1234567',
      address: 'Sudbury',
      isAdmin: true,
    },
  ];
  